server:
  port: 8081
datasource:
  host: localhost
  port: 3306
  name: yuurei001
  username: root
  password: wsy20010219
  charset: utf8mb4
  loc: Asia%2FShanghai
#datasource:
#  host: localhost
#  port: 3306
#  name: 20220726
#  username: root
#  password: root
#  charset: utf8mb4
#  loc: Asia%2FShanghai
#datasource:
#  host: 127.0.0.1
#  port: 3306
#  name: yuurei
#  username: root
#  password: 123456
#  charset: utf8mb4
#  loc: Asia%2FShanghai